
export const initialAnimeData = [
    { 
        title: "91 Days", 
        genres: ["Drama", "Thriller", "Crime"], 
        year: 2016, 
        img: "img/91_days.jpg", 
        studio: "Shuka", 
        stato: "Finito", 
        synopsis: "Nell'era del Proibizionismo a Lawless, la legge è dettata dalla mafia. Angelo Lagusa, dopo aver assistito al brutale sterminio della sua famiglia, vive nell'ombra finché una lettera anonima non gli offre l'occasione di vendicarsi. Sotto il nome di Avilio Bruno, si infiltra nel clan Vanetti, stringendo amicizia con il figlio del boss che deve uccidere. Una tragedia shakespeariana intrisa di sangue e whisky, dove la vendetta è un piatto che avvelena anche chi lo serve.", 
        structure: [{ name: "Stagione Unica", episodes: "12" }, { name: "OAV", episodes: "1" }], 
        links: { legal: [{ name: "Crunchyroll", url: "https://www.crunchyroll.com/91-days" }], illegal: [] } 
    },
    { 
        title: "Abenobashi Magical Shopping Street", 
        genres: ["Comedy", "Fantasy", "Parody"], 
        year: 2002, 
        img: "img/abenobashi.jpg", 
        studio: "Gainax", 
        stato: "Finito", 
        synopsis: "Sasshi e Arumi, amici d'infanzia cresciuti nel quartiere commerciale di Abenobashi a Osaka, si ritrovano catapultati in una serie di dimensioni parallele surreali. Ogni mondo è una distorsione folle dei loro interessi e paure: un mondo RPG, uno Sci-Fi, uno Hard Boiled. Dietro la comicità demenziale tipica della Gainax, si cela una storia toccante sulla paura di crescere, il rifiuto del cambiamento e l'inevitabilità di dire addio al passato.", 
        structure: [{ name: "Stagione Unica", episodes: "13" }], 
        links: { legal: [], illegal: [] } 
    },
    { 
        title: "Ajin: Demi-Human", 
        genres: ["Horror", "Thriller", "Supernatural"], 
        year: 2016, 
        img: "img/Ajin_Demi-Human.jpg", 
        studio: "Polygon Pictures", 
        stato: "Finito", 
        synopsis: "Gli Ajin sono una nuova sottospecie umana incapace di morire. Quando lo studente Kei Nagai viene investito da un camion e risorge immediatamente, la sua vita finisce: diventa il bersaglio del governo, che vuole catturarlo per crudeli esperimenti. In fuga da un'umanità che lo teme, Kei si trova coinvolto nel piano terroristico di Satou, un altro Ajin che vuole scatenare una guerra. Un thriller tattico dove l'immortalità è una maledizione.", 
        structure: [{ name: "Stagione 1", episodes: "13" }, { name: "Stagione 2", episodes: "13" }, { name: "Film Trilogy", episodes: "3" }], 
        links: { legal: [{ name: "Netflix", url: "https://www.netflix.com/title/80043576" }], illegal: [] } 
    },
    { 
        title: "Akame Ga Kill!", 
        genres: ["Action", "Fantasy", "Dark Fantasy"], 
        year: 2014, 
        img: "img/akame_ga_kill_.jpg", 
        studio: "White Fox", 
        stato: "Finito", 
        synopsis: "Tatsumi, un giovane guerriero di campagna, arriva nella Capitale imperiale con sogni di gloria, solo per scoprire che la città è un nido di corruzione inimmaginabile. Reclutato dai Night Raid, un gruppo di assassini che combatte per rovesciare l'Impero, scopre il prezzo della rivoluzione. In questo mondo, nessuno è al sicuro dal 'Game Over': eroi e cattivi muoiono con la stessa facilità in battaglie dove le Armi Imperiali dettano legge.", 
        structure: [{ name: "Stagione Unica", episodes: "24" }], 
        links: { legal: [{ name: "Crunchyroll", url: "https://www.crunchyroll.com/akame-ga-kill" }], illegal: [] } 
    },
    { 
        title: "Akira", 
        genres: ["Sci-Fi", "Cyberpunk"], 
        year: 1988, 
        img: "img/akira.jpg", 
        studio: "TMS Entertainment", 
        stato: "Film", 
        synopsis: "Neo-Tokyo, 2019. Trent'anni dopo la Terza Guerra Mondiale, la città è sull'orlo del collasso sociale. Kaneda, leader di una banda di motociclisti, cerca disperatamente di salvare il suo amico Tetsuo, rapito dai militari dopo un incidente. Tetsuo inizia a sviluppare poteri telecinetici devastanti che risvegliano il mistero di 'Akira', l'entità che distrusse la vecchia Tokyo. Un capolavoro visivo che esplora il potere, la corruzione e l'evoluzione umana.", 
        structure: [{ name: "Film", episodes: "1" }], 
        links: { legal: [{ name: "Netflix", url: "#" }], illegal: [] } 
    },
    { 
        title: "Akudama Drive", 
        genres: ["Sci-Fi", "Cyberpunk", "Action"], 
        year: 2020, 
        img: "img/akudama_drive.jpg", 
        studio: "Pierrot", 
        stato: "Finito", 
        synopsis: "Nel distretto del Kansai, soggiogato dal Kanto, scoppia il caos quando viene messa una taglia sulla testa di un condannato a morte. Una ragazza ordinaria si ritrova, per una serie di sfortunati equivoci, a fingersi una criminale di classe S ('Akudama') per sopravvivere in mezzo a serial killer, hacker e combattenti. Un heist-movie cyberpunk frenetico e visivamente esplosivo, dove l'unica regola è completare la missione o morire provandoci.", 
        structure: [{ name: "Stagione Unica", episodes: "12" }], 
        links: { legal: [{ name: "Crunchyroll", url: "https://www.crunchyroll.com/akudama-drive" }], illegal: [] } 
    },
    { 
        title: "Arcane: League of Legends", 
        genres: ["Fantasy", "Sci-Fi", "Drama"], 
        year: 2021, 
        img: "img/arcane_league_of_legends.jpg", 
        studio: "Fortiche", 
        stato: "Finito", 
        synopsis: "Sullo sfondo del divario incolmabile tra la ricca e progressista Piltover e la squallida città sotterranea di Zaun, si consuma la tragedia di due sorelle, Vi e Jinx. Separate da incomprensioni e traumi, si ritrovano su fronti opposti in una guerra alimentata dalla tecnologia Hextech e dalla droga Shimmer. Una narrazione matura che esplora la dualità umana, la politica e le conseguenze della violenza.", 
        structure: [{ name: "Stagione 1", episodes: "9" }, { name: "Stagione 2", episodes: "9" }], 
        links: { legal: [{ name: "Netflix", url: "https://www.netflix.com/title/81435684" }], illegal: [] } 
    },
    { 
        title: "Attack on Titan", 
        genres: ["Action", "Drama", "Fantasy"], 
        year: 2013, 
        img: "img/attack_on_titan.jpg", 
        studio: "MAPPA / Wit", 
        stato: "Finito", 
        synopsis: "Per un secolo, l'umanità ha vissuto come bestiame all'interno di tre mura concentriche, terrorizzata dai Titani. La caduta del Wall Maria cambia tutto per Eren Jaeger, che vede sua madre divorata. Giurando di sterminare ogni singolo Titano, si unisce all'esercito. Quella che inizia come una lotta per la sopravvivenza si trasforma in un complesso intrigo politico e filosofico sulla libertà, la storia riscritta e il ciclo infinito dell'odio.", 
        structure: [{ name: "S1", episodes: "25" }, { name: "S2", episodes: "12" }, { name: "S3", episodes: "22" }, { name: "S4 Final", episodes: "35" }], 
        links: { legal: [{ name: "Crunchyroll", url: "https://www.crunchyroll.com/attack-on-titan" }, { name: "Prime Video", url: "#" }], illegal: [] } 
    },
    { 
        title: "Berserk", 
        genres: ["Fantasy", "Horror", "Action"], 
        year: 1997, 
        img: "img/berserk.jpg", 
        studio: "OLM", 
        stato: "Finito", 
        synopsis: "Guts è un mercenario che non conosce altro che il campo di battaglia. La sua vita cambia quando incontra Griffith, il carismatico e ambizioso leader della Squadra dei Falchi, che lo sconfigge e lo obbliga a unirsi a loro. Tra battaglie campali e intrighi di corte, tra i due nasce un legame profondo, destinato però a essere spezzato dall'ambizione sfrenata di Griffith che porterà a un evento apocalittico indimenticabile.", 
        structure: [{ name: "Serie 1997", episodes: "25" }, { name: "Film Trilogy", episodes: "3" }, { name: "Serie 2016", episodes: "24" }], 
        links: { legal: [{ name: "Netflix", url: "#" }], illegal: [] } 
    },
    { 
        title: "Black Clover", 
        genres: ["Action", "Fantasy"], 
        year: 2017, 
        img: "img/black_clover.jpg", 
        studio: "Pierrot", 
        stato: "Finito", 
        synopsis: "Asta e Yuno sono orfani cresciuti insieme con lo stesso sogno: diventare l'Imperatore Magico. Ma c'è un problema: in un mondo dove la magia è tutto, Asta non ne possiede nemmeno una briciola. Rifiutandosi di arrendersi, ottiene un misterioso grimorio a cinque foglie che contiene il potere dell'anti-magia. Una storia classica di determinazione che scala verso battaglie contro demoni e divinità.", 
        structure: [{ name: "Serie TV", episodes: "170" }, { name: "Film: Sword of the Wizard King", episodes: "1" }], 
        links: { legal: [{ name: "Crunchyroll", url: "https://www.crunchyroll.com/black-clover" }], illegal: [] } 
    },
    { 
        title: "BLEACH", 
        genres: ["Action", "Supernatural"], 
        year: 2004, 
        img: "img/bleach.jpg", 
        studio: "Pierrot", 
        stato: "In corso", 
        synopsis: "Ichigo Kurosaki, un liceale in grado di vedere i fantasmi, assorbe accidentalmente i poteri di una Shinigami, Rukia. Costretto a sostituirla, inizia a purificare gli spiriti maligni (Hollow) e a proteggere i vivi. La sua avventura si espande ben oltre la sua città, portandolo nella Soul Society per sventare complotti millenari che minacciano l'equilibrio stesso tra la vita e la morte.", 
        structure: [{ name: "Serie Originale", episodes: "366" }, { name: "TYBW Part 1-3", episodes: "39" }, { name: "TYBW Part 4", episodes: "Attesa 2026" }], 
        links: { legal: [{ name: "Disney+", url: "#" }], illegal: [] } 
    },
    { 
        title: "BNA: Brand New Animal", 
        genres: ["Fantasy", "Sci-Fi"], 
        year: 2020, 
        img: "img/bna_brand_new_animal.jpg", 
        studio: "Trigger", 
        stato: "Finito", 
        synopsis: "Michiru Kagemori era una normale umana finché non si è trasformata inspiegabilmente in un uomo-bestia tanuki. Fugge ad Anima City, un rifugio per la sua nuova specie, dove incontra Shirou, un lupo che odia gli umani. Insieme indagano sul mistero della trasformazione di Michiru, scoprendo che la città utopica nasconde segreti oscuri legati alla genetica e alla segregazione.", 
        structure: [{ name: "Stagione Unica", episodes: "12" }], 
        links: { legal: [{ name: "Netflix", url: "https://www.netflix.com/title/81220435" }], illegal: [] } 
    },
    { 
        title: "Burn the Witch", 
        genres: ["Fantasy", "Action"], 
        year: 2020, 
        img: "img/burn_the_witch.jpg", 
        studio: "Studio Colorido", 
        stato: "Finito", 
        synopsis: "Mentre il mondo conosce Londra, esiste una 'Reverse London' invisibile dove i draghi sono reali e causano il 72% delle morti. Noel e Ninny sono streghe della Wing Bind, un'agenzia incaricata di gestire e proteggere (o eliminare) queste creature. Un breve ma intenso tuffo nell'universo espanso di Tite Kubo, pieno di stile urban-fantasy.", 
        structure: [{ name: "Serie ONA", episodes: "3" }, { name: "Il prequel #0.8", episodes: "1" }], 
        links: { legal: [{ name: "Crunchyroll", url: "https://www.crunchyroll.com/burn-the-witch" }], illegal: [] } 
    },
    { 
        title: "Chainsaw Man", 
        genres: ["Action", "Horror", "Dark Fantasy"], 
        year: 2022, 
        img: "img/chainsaw_man.jpg", 
        studio: "MAPPA", 
        stato: "In corso", 
        synopsis: "Denji è un ragazzo povero che venderebbe i suoi organi pur di saldare i debiti del padre. Tradito e ucciso, rinasce grazie al patto con Pochita, il suo diavolo-motosega domestico, diventando Chainsaw Man. Reclutato dalla Pubblica Sicurezza, caccia diavoli spietati solo per inseguire sogni semplici: buon cibo e una ragazza. Un'opera caotica e viscerale che decostruisce lo shonen classico.", 
        structure: [{ name: "Stagione 1", episodes: "12" }, { name: "Film: Reze Arc", episodes: "1 (2025)" }, { name: "Stagione 2", episodes: "TBH" }], 
        links: { legal: [{ name: "Crunchyroll", url: "https://www.crunchyroll.com/chainsaw-man" }], illegal: [] } 
    },
    { 
        title: "Claymore", 
        genres: ["Fantasy", "Action"], 
        year: 2007, 
        img: "img/claymore.jpg", 
        studio: "Madhouse", 
        stato: "Finito", 
        synopsis: "In un medioevo infestato dagli Yoma, mostri che si cibano di viscere umane assumendone l'aspetto, l'unica difesa sono le Claymore: guerriere dagli occhi d'argento, ibride per metà umane e metà Yoma. Clare, la più debole dell'organizzazione, viaggia spinta da una vendetta personale, lottando non solo contro i mostri, ma contro la sua stessa natura che rischia di prendere il sopravvento.", 
        structure: [{ name: "Stagione Unica", episodes: "26" }], 
        links: { legal: [], illegal: [] } 
    },
    { 
        title: "Cyberpunk: Edgerunners", 
        genres: ["Sci-Fi", "Cyberpunk", "Tragedy"], 
        year: 2022, 
        img: "img/cyberpunk__edgerunners.jpg", 
        studio: "Trigger", 
        stato: "Finito", 
        synopsis: "A Night City, dove la tecnologia e le modifiche corporee sono un'ossessione, David Martinez perde tutto in un giorno. Per sopravvivere, si fa impiantare un potenziamento militare illegale e diventa un Edgerunner, un mercenario fuorilegge. In una corsa frenetica verso la fama e l'inevitabile autodistruzione, David scopre che in questa città non ci sono lieto fine, solo leggende che bruciano in fretta.", 
        structure: [{ name: "Stagione Unica", episodes: "10" }], 
        links: { legal: [{ name: "Netflix", url: "https://www.netflix.com/title/81054853" }], illegal: [] } 
    },
    { 
        title: "DAN DA DAN", 
        genres: ["Action", "Comedy", "Supernatural"], 
        year: 2024, 
        img: "img/dan_da_dan.jpg", 
        studio: "Science SARU", 
        stato: "In corso", 
        synopsis: "Momo crede nei fantasmi ma non negli alieni; Okarun crede negli alieni ma non nei fantasmi. Per provarsi a vicenda di avere torto, visitano luoghi infestati, finendo per scoprire che *entrambi* esistono. Travolti da spiriti turbo-nonne e alieni pervertiti, i due devono unire forze occulte e sci-fi in una commedia romantica d'azione ad altissimo numero di ottani e bizzarria.", 
        structure: [{ name: "Stagione 1", episodes: "12" }, { name: "Stagione 2", episodes: "Annunciata" }], 
        links: { legal: [{ name: "Netflix", url: "#" }, { name: "Crunchyroll", url: "#" }], illegal: [] } 
    },
    { 
        title: "Darwin's Game", 
        genres: ["Action", "Thriller", "Survival"], 
        year: 2020, 
        img: "img/darwin_s_game.jpg", 
        studio: "Nexus", 
        stato: "Finito", 
        synopsis: "Kaname Sudo apre un'app misteriosa chiamata 'Darwin's Game' e viene morso da un serpente digitale. Senza volerlo, è entrato in un battle royale urbano dove i giocatori si sfidano all'ultimo sangue usando poteri sovrannaturali chiamati Sigil. Rifiutando la logica dell'uccidere o essere uccisi, Kaname cerca di formare un clan per porre fine al gioco macabro dall'interno.", 
        structure: [{ name: "Stagione 1", episodes: "11" }], 
        links: { legal: [{ name: "Netflix", url: "#" }], illegal: [] } 
    },
    { 
        title: "Deadman Wonderland", 
        genres: ["Sci-Fi", "Horror", "Gore"], 
        year: 2011, 
        img: "img/deadman_wonderland.jpg", 
        studio: "Manglobe", 
        stato: "Finito", 
        synopsis: "Dieci anni dopo un grande terremoto a Tokyo, Ganta Igarashi è l'unico sopravvissuto al massacro della sua classe. Incastrato per il crimine, viene mandato a Deadman Wonderland, una prigione privata che è anche un parco divertimenti dove i detenuti rischiano la vita per intrattenere il pubblico. Lì scopre di poter manipolare il proprio sangue come un'arma, entrando nel brutale torneo 'Carnival Corpse'.", 
        structure: [{ name: "Stagione Unica", episodes: "12" }, { name: "OAV", episodes: "1" }], 
        links: { legal: [], illegal: [] } 
    },
    { 
        title: "Death Note", 
        genres: ["Thriller", "Psychological", "Supernatural"], 
        year: 2006, 
        img: "img/death_note.jpg", 
        studio: "Madhouse", 
        stato: "Finito", 
        synopsis: "Light Yagami, studente geniale annoiato dalla vita, trova il Death Note, un quaderno perduto da uno Shinigami. Chiunque il cui nome venga scritto su di esso muore. Ebbro di potere divino, Light decide di ripulire il mondo dai criminali sotto lo pseudonimo 'Kira'. A ostacolarlo c'è L, il miglior detective del mondo. Una partita a scacchi intellettuale dove la prima mossa falsa significa morte.", 
        structure: [{ name: "Stagione Unica", episodes: "37" }], 
        links: { legal: [{ name: "Netflix", url: "https://www.netflix.com/title/70204970" }], illegal: [] } 
    },
    { 
        title: "Deca-Dence", 
        genres: ["Sci-Fi", "Action", "Adventure"], 
        year: 2020, 
        img: "img/deca_dence.jpg", 
        studio: "NUT", 
        stato: "Finito", 
        synopsis: "L'umanità, quasi estinta dai mostri Gadoll, vive nella fortezza mobile Deca-Dence. Natsume, una ragazza orfana che sogna di combattere, finisce a lavorare nella manutenzione sotto la guida di Kaburagi, un riparatore apatico. Scoprirà presto che il mondo non è quello che sembra e che Deca-Dence nasconde una verità che va oltre la semplice sopravvivenza, sfidando l'ordine costituito del sistema.", 
        structure: [{ name: "Stagione Unica", episodes: "12" }], 
        links: { legal: [{ name: "Crunchyroll", url: "https://www.crunchyroll.com/deca-dence" }], illegal: [] } 
    },
    { 
        title: "Demon Slayer", 
        genres: ["Action", "Fantasy", "Historical"], 
        year: 2019, 
        img: "img/demon_slayer.jpg", 
        studio: "Ufotable", 
        stato: "In corso", 
        synopsis: "Giappone, periodo Taisho. Tanjiro torna a casa e trova la famiglia massacrata; solo la sorella Nezuko respira, ma è diventata un demone. Tanjiro impugna la spada per trovare una cura e vendicare i suoi cari. Un'opera che eleva lo shonen classico grazie a un'animazione mozzafiato, dove la gentilezza del protagonista si scontra con la brutalità di nemici terrificanti.", 
        structure: [{ name: "S1", episodes: "26" }, { name: "Mugen Train", episodes: "7" }, { name: "S2 District", episodes: "11" }, { name: "S3 Villaggio", episodes: "11" }, { name: "S4 Training", episodes: "8" }, { name: "Infinity Castle Movies", episodes: "In Uscita 2026" }], 
        links: { legal: [{ name: "Crunchyroll", url: "#" }, { name: "Netflix", url: "#" }], illegal: [] } 
    },
    { 
        title: "Devil May Cry", 
        genres: ["Action", "Fantasy"], 
        year: 2025, 
        img: "img/devil_may_cry.jpg", 
        studio: "Studio Mir", 
        stato: "Finito", 
        synopsis: "Dante, il cacciatore di demoni figlio del leggendario Sparda, gestisce la sua agenzia 'Devil May Cry' tra debiti e pizze. Quando una minaccia demoniaca emerge per aprire un portale verso il mondo umano, Dante sfodera le sue pistole Ebony & Ivory e la spada Rebellion. Adattamento stiloso e adrenalinico che porta l'azione 'Stylish' del videogioco nell'animazione.", 
        structure: [{ name: "Stagione 1", episodes: "8" }], 
        links: { legal: [{ name: "Netflix", url: "#" }], illegal: [] } 
    },
    { 
        title: "Devilman Crybaby", 
        genres: ["Horror", "Supernatural", "Avant-Garde"], 
        year: 2018, 
        img: "img/devilman_crybaby.jpg", 
        studio: "Science SARU", 
        stato: "Finito", 
        synopsis: "Akira Fudo è un ragazzo dal cuore tenero che piange per gli altri. Il suo amico Ryo lo trascina in un sabbat per svelare l'esistenza dei demoni. Akira si fonde con Amon, il più potente di essi, diventando un Devilman: corpo di demone, cuore umano. Una rivisitazione psichedelica e ultraviolenta di Go Nagai che esplora la degenerazione della società e l'amore in un mondo che corre verso l'apocalisse.", 
        structure: [{ name: "Stagione Unica", episodes: "10" }], 
        links: { legal: [{ name: "Netflix", url: "https://www.netflix.com/title/80174601" }], illegal: [] } 
    },
    { 
        title: "Drifters", 
        genres: ["Fantasy", "Action", "Isekai"], 
        year: 2016, 
        img: "img/drifters.jpg", 
        studio: "Hoods", 
        stato: "Finito", 
        synopsis: "Shimazu Toyohisa, samurai della battaglia di Sekigahara, ferito a morte, si ritrova in un corridoio bianco pieno di porte. Viene spedito in un mondo fantasy dove guerrieri storici (i 'Drifters', tra cui Nobunaga e Annibale) combattono contro gli 'Ends' (come Giovanna d'Arco e Rasputin) che vogliono distruggere l'umanità. Una guerra totale e cruenta tra le più grandi menti militari della storia.", 
        structure: [{ name: "Stagione 1", episodes: "12" }, { name: "OAV 13-15", episodes: "3" }], 
        links: { legal: [], illegal: [] } 
    },
    { 
        title: "Erased", 
        genres: ["Thriller", "Mystery", "Supernatural"], 
        year: 2016, 
        img: "img/erased.jpg", 
        studio: "A-1 Pictures", 
        stato: "Finito", 
        synopsis: "Satoru Fujinuma possiede il 'Revival', un fenomeno che lo manda indietro nel tempo di pochi minuti per prevenire tragedie. Quando sua madre viene uccisa, viene catapultato indietro di 18 anni, nel corpo del se stesso bambino. Deve risolvere il mistero dei rapimenti seriali che colpirono la sua classe nel 1988 per salvare il futuro e le persone che ama.", 
        structure: [{ name: "Stagione Unica", episodes: "12" }], 
        links: { legal: [{ name: "Netflix", url: "https://www.netflix.com/title/80114225" }], illegal: [] } 
    },
    { 
        title: "Failure Frame", 
        genres: ["Fantasy", "Isekai", "Revenge"], 
        year: 2024, 
        img: "img/failure_frame.jpg", 
        studio: "Seven Arcs", 
        stato: "Finito", 
        synopsis: "L'intera classe di Mimori Touka viene evocata in un altro mondo per servire come eroi. Mentre i suoi compagni ricevono ranghi alti, lui è un Rango E con abilità di 'Stato alterato' apparentemente inutili. La Dea lo getta in un dungeon per morire. Lì, Touka scopre che i suoi poteri sono letali se usati con astuzia, e inizia la sua risalita dall'inferno giurando vendetta contro la Dea e chi lo ha tradito.", 
        structure: [{ name: "Stagione 1", episodes: "12" }], 
        links: { legal: [{ name: "Crunchyroll", url: "#" }], illegal: [] } 
    },
    { 
        title: "Fate/Zero", 
        genres: ["Action", "Fantasy", "Thriller"], 
        year: 2011, 
        img: "img/fate_zero.jpg", 
        studio: "Ufotable", 
        stato: "Finito", 
        synopsis: "La Quarta Guerra del Santo Graal. Sette maghi evocano sette Spiriti Eroici per contendersi il calice onnipotente. Al centro c'è Kiritsugu Emiya, il 'Mago Assassino', un uomo disposto a tutto pur di salvare il mondo, anche se significa uccidere chiunque ostacoli la pace. Un'opera cupa e filosofica dove gli ideali di cavalleria si scontrano con la spietata realtà della guerra moderna.", 
        structure: [{ name: "Stagione 1", episodes: "13" }, { name: "Stagione 2", episodes: "12" }], 
        links: { legal: [{ name: "Netflix", url: "#" }], illegal: [] } 
    },
    { 
        title: "FLCL", 
        genres: ["Sci-Fi", "Comedy", "Surreal"], 
        year: 2000, 
        img: "img/flcl.jpg", 
        studio: "Gainax / Production I.G", 
        stato: "Finito", 
        synopsis: "Naota è un dodicenne annoiato dalla vita di provincia. Tutto cambia quando Haruko, una donna pazza su una Vespa gialla, lo investe e lo colpisce in testa con un basso Rickenbacker. Dalla bozza sulla sua fronte iniziano a uscire robot, mentre Haruko si stabilisce a casa sua. Una metafora esplosiva e rock'n'roll della pubertà, dove il non-sense nasconde profonde verità sulla crescita.", 
        structure: [{ name: "FLCL Classic", episodes: "6" }, { name: "Progressive", episodes: "6" }, { name: "Alternative", episodes: "6" }, { name: "Grunge", episodes: "3" }, { name: "Shoegaze", episodes: "3" }], 
        links: { legal: [], illegal: [] } 
    },
    { 
        title: "Fullmetal Alchemist: Brotherhood", 
        genres: ["Adventure", "Fantasy", "Steampunk"], 
        year: 2009, 
        img: "img/fullmetal_alchemist__brotherhood.jpg", 
        studio: "Bones", 
        stato: "Finito", 
        synopsis: "Edward e Alphonse Elric hanno violato il tabù definitivo dell'alchimia: la trasmutazione umana. Hanno pagato a caro prezzo: Ed ha perso un braccio e una gamba, Al l'intero corpo. Ora viaggiano come Cani dell'Esercito cercando la Pietra Filosofale per riottenere ciò che hanno perso, scoprendo che il loro paese, Amestris, è costruito su un cerchio di sangue e bugie.", 
        structure: [{ name: "Serie TV", episodes: "64" }], 
        links: { legal: [{ name: "Netflix", url: "#" }], illegal: [] } 
    },
    { 
        title: "Future Diary", 
        genres: ["Thriller", "Survival", "Romance"], 
        year: 2011, 
        img: "img/future_diary.jpg", 
        studio: "Asread", 
        stato: "Finito", 
        synopsis: "Yuki è un osservatore passivo che scrive un diario sul cellulare. Il Dio del Tempo e dello Spazio, Deus, trasforma il suo diario in un 'Diario del Futuro' e lo iscrive in un battle royale con altri 11 detentori. L'obiettivo: uccidersi a vicenda per diventare il nuovo Dio. A proteggerlo c'è Yuno Gasai, una ragazza innamorata di lui alla follia... una follia omicida e terrificante.", 
        structure: [{ name: "Serie TV", episodes: "26" }, { name: "Redial OAV", episodes: "1" }], 
        links: { legal: [], illegal: [] } 
    },
    { 
        title: "Gachiakuta", 
        genres: ["Action", "Fantasy", "Urban"], 
        year: 2025, 
        img: "img/gachiakuta.jpg", 
        studio: "Bones", 
        stato: "In corso", 
        synopsis: "Rudo vive ai margini di una città che getta i suoi rifiuti nell'Abisso sottostante. Accusato ingiustamente dell'omicidio del padre adottivo, viene gettato lui stesso nell'Abisso. Qui scopre che la spazzatura ha un'anima e può diventare un'arma (Jinki). Unendosi ai 'Pulitori', Rudo combatte le bestie di immondizia per risalire e vendicarsi di chi lo ha gettato via come uno scarto.", 
        structure: [{ name: "Stagione 1", episodes: "24" }], 
        links: { legal: [{ name: "Crunchyroll", url: "#" }], illegal: [] } 
    },
    { 
        title: "Gangsta.", 
        genres: ["Action", "Drama", "Crime"], 
        year: 2015, 
        img: "img/gangsta_.jpg", 
        studio: "Manglobe", 
        stato: "Finito", 
        synopsis: "Ergastulum è una città marcia, rifugio per mafia, prostitute e 'Twilight' (super-soldati mercenari drogati). Worick e Nicolas gestiscono l'agenzia 'Benriya', accettando lavori che né la polizia né la mafia vogliono toccare. Un noir crudo e realistico che esplora la discriminazione e la lealtà in un mondo dove la speranza è solo una droga costosa.", 
        structure: [{ name: "Stagione Unica", episodes: "12" }], 
        links: { legal: [], illegal: [] } 
    },
    { 
        title: "Gantz", 
        genres: ["Sci-Fi", "Horror", "Psychological"], 
        year: 2004, 
        img: "img/gantz.jpg", 
        studio: "Gonzo", 
        stato: "Finito", 
        synopsis: "Kei Kurono muore investito dalla metro e si risveglia in una stanza con una sfera nera, Gantz. Lui e altri defunti sono costretti a partecipare a missioni notturne: cacciare alieni grotteschi che vivono sulla Terra. Se sopravvivi, guadagni punti per la libertà; se muori, è la fine definitiva. Un'opera cinica e violenta sulla natura umana messa alle strette.", 
        structure: [{ name: "Stagione 1", episodes: "13" }, { name: "Stagione 2", episodes: "13" }], 
        links: { legal: [], illegal: [] } 
    },
    { 
        title: "Gate", 
        genres: ["Fantasy", "Military", "Isekai"], 
        year: 2015, 
        img: "img/gate.jpg", 
        studio: "A-1 Pictures", 
        stato: "Finito", 
        synopsis: "Un portale appare a Ginza, Tokyo, vomitando orchi e draghi. Le forze di autodifesa giapponesi respingono l'invasione e attraversano il portale. Itami, un otaku ufficiale dell'esercito, guida una spedizione in questo mondo fantasy. Invece della guerra totale, la storia si concentra sullo scontro culturale, la politica e l'impatto della tecnologia moderna (carri armati contro draghi) in un impero medievale.", 
        structure: [{ name: "Stagione 1", episodes: "12" }, { name: "Stagione 2", episodes: "12" }], 
        links: { legal: [], illegal: [] } 
    },
    { 
        title: "Grimgar of Fantasy and Ash", 
        genres: ["Fantasy", "Isekai", "Drama"], 
        year: 2016, 
        img: "img/grimgar_of_fantasy_and_ash.jpg", 
        studio: "A-1 Pictures", 
        stato: "Finito", 
        synopsis: "Un gruppo di ragazzi si sveglia nel mondo di Grimgar senza ricordi. Non sono gli eroi prescelti; sono quelli rimasti indietro, costretti a formare un party per sopravvivere come soldati volontari. La serie si distingue per il suo realismo brutale: uccidere il goblin più debole è una lotta disperata, l'equipaggiamento costa caro e la morte di un compagno è definitiva e straziante.", 
        structure: [{ name: "Stagione Unica", episodes: "12" }], 
        links: { legal: [{ name: "Crunchyroll", url: "https://www.crunchyroll.com/grimgar-ashes-and-illusions" }], illegal: [] } 
    },
    { 
        title: "Gurren Lagann", 
        genres: ["Mecha", "Sci-Fi", "Action"], 
        year: 2007, 
        img: "img/gurren_lagann.jpg", 
        studio: "Gainax", 
        stato: "Finito", 
        synopsis: "Simon, un timido scavatore, e Kamina, un vulcano di carisma, vivono nel sottosuolo oppressi dal Re Spirale. Trovando il mecha Lagann,sfondano il soffitto verso il cielo. Quello che inizia come una ribellione contro gli Uomini-Bestia scala esponenzialmente fino a diventare una battaglia cosmica, alimentata dalla sola forza di volontà e dalla trivella che perforerà i cieli!", 
        structure: [{ name: "Serie TV", episodes: "27" }, { name: "Film: Gurren-hen", episodes: "1" }, { name: "Film: Lagann-hen", episodes: "1" }], 
        links: { legal: [{ name: "Netflix", url: "#" }], illegal: [] } 
    },
    { 
        title: "Handyman Saitou in Another World", 
        genres: ["Fantasy", "Isekai", "Slice of Life"], 
        year: 2023, 
        img: "img/handyman_saitou_in_another_world.jpg", 
        studio: "C2C", 
        stato: "Finito", 
        synopsis: "Saitou è un tuttofare comune che non si è mai sentito apprezzato. Trasportato in un mondo fantasy, si unisce a un party disfunzionale: una guerriera tsundere, un mago senile e una fata avida. Qui scopre che le sue abilità 'banali' (scassinare, riparare armature, fare calcoli) sono vitali. Una serie dolce e divertente che mostra come ognuno possa essere l'eroe di qualcuno.", 
        structure: [{ name: "Stagione 1", episodes: "12" }], 
        links: { legal: [{ name: "Crunchyroll", url: "#" }], illegal: [] } 
    }
];
